### ISSUE TITLE
Feedback for guides

### ISSUE THREAD

**Issue by yihangho** [CS2103AUG2016-W11-C1/main#104]
# User Guide
1. Too lengthy
2. Clash between conversational and technical tone
3. Merge some commands on TOC (e.g., done and undone; today and tomorrow)
4. No need to be too creative.
5. Actual link in brackets

Introduction
1. `alone` is extra
2. Not sure if affinity for typing is appropriate

Getting started
1. Where is the release tab? (Perhaps we don't even need the screenshot if we have link)

Visual Walkthrough
1. Superimpose on top of actual screenshot

Functional Walkthrough
1. Not sure if it's necessary
2. Can use in the software demo

Command summary
1. Rephrase `multiple words`.
2. Use examples to show multiple words instead of using dots.
3. KEYWORD(S) might be clearer.

Commands
1. Repeat case-insensitivity & order not important in command summary.
2. Change // to something else, e.g., bullet point.

Add
1. Can move description of tags to other command.

Remind
1. Fun fact is not fun.
2. Ever wondered -> If you wonder
3. Remove behind the scene
4. Show screenshot of multiple search results when there's ambiguity
5. Update example -> note is now compulsory

Edit
1. Cut it down, not completely
2. "Any new tags you add will replace all exising tags."

Editr
1. Refactor "this is a variant of edit command but for reminders"

Rename
1. Refactor "all tasks with that tag to the new tag"

Done
1. Remove `would you`?
2. Remove dot at the end of example.

Delete

Freetime
1. Show screenshot perhaps.

Today
1. "All events that occur today."

Tomorrow
1. "All events that occur tomorrow."

Undo
1. "the following command(S)"

Help
1. "we will tell you all that you need to know" -> what you actually show
2. Perhaps move to the end, show screenshot and double as command summary.

Exit
1. Too much, sounds like someone is dying.
2. Not necessary to say that it's equivalent to clicking X.

Conclusion
1. Issue tracker -> show link
# Developer Guide

Introduciton
1. "being an open-source projects, we"
2. "who wants"

Setting Up
1. Link

Coding Standards
1. Link
1. 1 command -> one command
2. At most one command

CI
1. following things -> what things
2. dependecies -> dependencies
1. Is the architecture acceptable?
2. Sequence diagram.
3. Dev ops is like text book rather than instructional.

Submit by Nov 7. Email if need feedback.
1. Mention that we need to add command to CommandManager when adding a new command.

Presentation
1. Introduction
- Good morning & address the audience (how, since audience is not the user)
- The problem statement
- How our app solve the problem
  1. The software
  2. Functionalities of the system
- Add
- Today & tomorrow
- Done
- Remind
- Path
  1. Special functionalities and how they work
- Freetime
- Alias
- Shortcuts
- Command suggestion
- Undo
  1. Conclusion

**Comment by Roahhh** [comment]
Made most of the textual changes in user guide. Still need to add screenshots.
