### ISSUE TITLE
T10 V0.4 Feedback

### ISSUE THREAD

**Issue by cmkumar87** [CS2103AUG2016-W11-C1/main#113]
- Collated Code doc still has only the src doc; tests and doc not collated yet. So I will review just the collated code.
General Feedback on the product:
- UI needs lot of improvement before it is dogfood ready (highlight changes when tasks move from one pane to the next). 
- The user feedback that appears in the last column isn't catching the eye. Generally, its a weird place in an UI centric app to show feedback. Feedback displayed on horizontal text box/pane at the top or bottom will look better. This will also free up panel space for you.
- I like your idea to keep the last pane (or any one pane) dynamic and use it for different purposes. So, as discussed, leave the help there by default and use it list other things when required.
- Finish pending work on docs, About Us.
- Wrap up milestones before coming to tutorial, going forward.

**Comment by cadmusthefounder** [comment]
Issues noted in #114  and #112
