### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cadmusthefounder** [CS2103AUG2016-W11-C1/main#114]
Must Do:
- [x]  Update command summary table for deleter, path, undone, unalias for BOTH user and dev guide.
- [x]  Create explanation in the same format as the rest of the command for those not in table and user guide.
- [x]  Create link in table of contents.
- [x] Dev guide use case formatting can be improved a lot i think.
- [x]  Dev guide product survey can be neater and more focused. I think instead of the table and the list of cons, can focus on one area lets say UI, do a comparison then do a lesson learnt and if it fits our target audience.
- [x]  Activity/OO diagram
- [x]  Notable API

Good to do:
- [x]  this one https://github.com/nus-cs2103/website/blob/master/contents/teams.md

**Comment by cadmusthefounder** [comment]
11) Notable APIs

**Comment by Roahhh** [comment]
Shifting to v0.5 for finalized ver.
