### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by Roahhh** [CS2103AUG2016-W11-C1/main#21]

**Comment by cadmusthefounder** [comment]
On program launch, the following items should be first displayed:

1) Todo Panel
- List of all todos in alphabetical order.

2) Deadline Panel
- List of all deadlines today, sorted by urgency

3) Calendar Panel
- List of all events for the next 3 days.

4) Display Panel
- List of all reminders for the day, sorted by urgency
