### ISSUE TITLE
Update search function to include reminder names

### ISSUE THREAD

**Issue by Roahhh** [CS2103AUG2016-W11-C1/main#30]
Need to update commands before closing

**Comment by cadmusthefounder** [comment]
Commands that requires this:

1) Delete
2) Edit
3) View
4) List
5) Today

**Comment by cadmusthefounder** [comment]
Oops wait remove Edit

**Comment by cadmusthefounder** [comment]
remove View also

**Comment by Kaiiiii** [comment]
Create searchr function

**Comment by Roahhh** [comment]
Searchr function created by @Kaiiiii

**Comment by Roahhh** [comment]
Change delete to deleter
