### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by cmkumar87** [CS2103AUG2016-W11-C1/main#35]
* As said during the tutorial, a critical issue is lack of systematic tracking of user stories and completion status. Please add a issue for each story, assign it to a member and add it to a milestone. When you reach the milestone you are expected to have completed the task, closed the issue and added the feature to the release.
* User Guide or Readme: Add a mockup of your app (UI) similar to addressbook app you were provided.
* User Guide: It is not clear what Freetime does. Please update the description. 
* Dev Guide: Appendices were expected to have been completed by V0.2. Not even the Use Cases are up!! Your process and documentation are equally important as your code. I am unable to provide further feedback for T8A3 with the current status of your docs.
* Dev Guide: Proof read User stories for typos. for e.g., "search a task" is better written as "search for a task"

**Comment by yihangho** [comment]
@cmkumar87 Thanks for your feedback. Regarding the user guide and developer guide, please look at the [guides branch](https://github.com/CS2103AUG2016-W11-C1/main/tree/guides/doc) for the latest copy. The reason we're doing it in another branch is that we're still making amendments for the CS2101 version.

**Comment by cmkumar87** [comment]
Okay. I will review those. Please point to those in the readme here if you haven't done so yet.

**Comment by cmkumar87** [comment]
* Appendix E : Product Survey not done yet. We are past the deadline for this. 

* Appendix B : Use Cases
Add Task
Not clear how Task manager categorises the task. If more inputs are provided by the user to enable this specify those in step 1.
Merge 3 and 4 since there is no user interaction after 3

List Task
What will you do if there are a large number of tasks to be shown? Is the use case useful? You may want to limit the view by tasks that are due today or the next 3 days or by priority.
Also, the homepage/landing page  can show such a list by default without a command. I don't remember what your home page shows currently.

Add Reminder
Why are you confusing the search use case with the add reminder. That is, solve only the problem that the use case is meant to solve. Finding a task using search parameter is a separate use case. Add reminder can make use of this use case. 

Mark task as done
Same comment as above.
Again no user interaction between 2 and 3. Merge them or indicate any user response you expect in between.



Minor Comments:
* Markups aren't okay. No indentations. 
* Appendix C : Non Functional Requirements
# 1 and # 8 are duplicates

**Comment by cadmusthefounder** [comment]
@cmkumar87 Issues noted. We will work on these things you mention by v0.3. Thanks for the feedback. Just one clarification regarding the minor comments, which portion of the guide has indentation issues? 

P.S. I have already merged the guides branch back to master branch.

**Comment by cmkumar87** [comment]
@cadmusthefounder Please see indentations and the mark up in Appendix B: Use Cases
https://github.com/CS2103AUG2016-W11-C1/main/blob/master/doc/DeveloperGuide.md

**Comment by Roahhh** [comment]
Did the amendments to Annexes B and E. It is now in the branch new-guides. 
Will further amend other things in dev guide, before merging with main branch by today.
