### ISSUE TITLE
Fix category tag in user guide

### ISSUE THREAD

**Issue by Kaiiiii** [CS2103AUG2016-W11-C1/main#51]
In user guide, examples for add show: 

"add... `#Category`" 

but the format is shown as:
"add... `#/Category`"

I have implemented the category the second way

Also, I implemented categories as `[#/CATEGORIES...]` (separated by space) instead of `[#/CATEGORIES]...`

**Comment by cadmusthefounder** [comment]
Your implementation makes more sense anyway

**Comment by Roahhh** [comment]
Verified the changes in new-guides branch. Closing issue.
