### ISSUE TITLE
setResponse method in various command classes

### ISSUE THREAD

**Issue by yihangho** [CS2103AUG2016-W11-C1/main#65]
The `setResponse` method in various command classes (for e.g., [DeleteCommand](https://github.com/CS2103AUG2016-W11-C1/main/blob/f7ba960b1b47689d63a403d38c821e3285eae991/src/main/java/linenux/command/DeleteCommand.java#L122)) is misleading. It does not set response, it sets `requiresUserResponse`, `foundTasks`, and `argument`.

**Comment by cadmusthefounder** [comment]
@yihangho Tbh i didnt know how to name it

**Comment by cadmusthefounder** [comment]
issue noted at #115
