### ISSUE TITLE
Change Tags format

### ISSUE THREAD

**Issue by cadmusthefounder** [CS2103AUG2016-W11-C1/main#68]
I realised there might be some confusion regarding the tags.

Should it be case:

1) [#/TAGS...]...
- means that each tag can have multiple words but to have multiple tags it should be 
- add task #/hello world #/bye
- so task is in the group hello world and bye

2) [#/TAGS...]

- allow each tag to only have one word
- add task #/hello world
- so task is in group hello and world

3) Alternate interpretation of 2

- each tag can have multiple words but one task can only have 1 tag
- add task #/hello world
- task is in group hello world.

4) [#/TAGS]...

- each tag is single word
- add task #/hello #/world
- task is in group hello and world

**Comment by cadmusthefounder** [comment]
Overwhelming vote to 1

**Comment by yihangho** [comment]
@cadmusthefounder it's called unanimity

**Comment by Kaiiiii** [comment]
Implemented. Can I close this issue now or do you still need it for the docs?

**Comment by cadmusthefounder** [comment]
can close alr
