### ISSUE TITLE
Make note in reminder compulsory

### ISSUE THREAD

**Issue by cadmusthefounder** [CS2103AUG2016-W11-C1/main#73]
This is important for the editr command. Otherwise there be a problem

Lets say

// Setting a reminder for the deadline 'pay utility bills' without any notes.
> remind pay utility bills t/2016-10-15 06:00pm 

// Adding a note to the reminder.
> editr pay utility bills n/withdraw money

so if there are multiple pay utility bills task, awaitingUserResponse is set true once and if that task has 5 reminders, user has to respond again, Thus destroying our code

**Comment by yihangho** [comment]
Merged in #92.
