### ISSUE TITLE
T9 (v0.3) Feedback

### ISSUE THREAD

**Issue by cmkumar87** [CS2103AUG2016-W11-C1/main#95]
- Your milestones are showing issues only from v0.3. It looks as though the product didn't exist at v0.2! Please record the older issues as well, assign it the person who did them and close them (unless github has some mechanism that stops these retrospective additions).

-  Please add class diagrams and seq, interaction diagrams (where  appropriate) to the Dev guide.
[To be Updated]

**Comment by cadmusthefounder** [comment]
compiled in issue #114  for documentation
